import type { NextPage } from "next";
import Head from "next/head";
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sub Network Connections</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>test</h1>

        <Image
          src="https://sub.id/images/kusama.svg"
          alt="icon-img"
          width={50}
          height={50}
        />
      </main>
    </div>
  );
};

export default Home;
